name: CI

on: [push, pull_request]

jobs:
  tests:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
        
    - name: Build Android application
      run: ./gradlew build

    - name: Run application tests
      run: ./gradlew test

